### ISSUE TITLE
Android Compatibility: Support for API Level 21

### ISSUE THREAD

**Issue by lovelessX** [4itworks/opensource_qwkin_dart#22]
Last September the Android minimum API level was reduced to 21, but as part of the V2 embedding update it was put back to 23. Is this necessary? Can we revert back to v21 for minimum support?

**Comment by lovelessX** [comment]
I've added a pull request for this issue.

**Comment by joaopereirajp** [comment]
@lovelessX, thank you for helping us! Your PR has been merged and will be published soon.
