### ISSUE TITLE
torch_controller required permissions

### ISSUE THREAD

**Issue by ilkamo** [4itworks/opensource_qwkin_dart#25]
Hi @AmirMostafavi @joaopereirajp @rafaelcmm @WilliamCunhaCardoso 👋 First of all, thanks for this package and for your work. I created an Android application which doesn't require camera access. It checks if the user's device supports the torch and displays an additional button if it is available.

The **torch_controller** package allows checking if the device has a torch and it works like a charm. However, I have a problem with the required permissions/features. According to the torch_controller `AndroidManifest.xml`, all the following permissions are required.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.example.torch_controller">
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-feature android:name="android.hardware.camera.flash" />
</manifest>
```

It means that if a device has no torch or camera, the application using your `torch_controller` package cannot be installed because the device will be marked as unsupported. Is there a way to make the presence of the torch/camera not mandatory?

I want to use something like this on all devices, with and without a torch/camera:

```
final controller = TorchController();
final isTorchAvailable = await controller.hasTorch;

if (isTorchAvailable) {
    // display the button for torch control
}
```

It would be great to use your package but if I do that I lose compatibility with many devices.
<img width="1136" alt="Screenshot 2022-06-26 at 19 32 49" src="https://user-images.githubusercontent.com/1657091/175827666-af26c560-d307-47e1-ac39-401ee18262c9.png">

**Comment by WilliamCunhaCardoso** [comment]
Thanks for your submitting and report! Going to work as soon I get free.

**Comment by rafaelcmm** [comment]
Hi @kamy22 , first of all thanks for your positive feedback and contribution.

You seem to have opened a pull request to your fork with a fix on this link: https://github.com/kamy22/opensource_qwkin_dart/pull/1/files

Did it work? If yes, do you mind to open a PR to our project? So we can run CI steps, and merge if it works?

Before open the PR, please remind to:

- Update CHANGELOG.md following our standard
- Update pubspec.yaml patch version

**Comment by joaopereirajp** [comment]
@rafaelcmm, I created a PR to fix this issue.

https://github.com/4itworks/opensource_qwkin_dart/pull/26

**Comment by ilkamo** [comment]
Only now have I noticed the response to my comment, thanks for taking care of the issue! @joaopereirajp @rafaelcmm @WilliamCunhaCardoso
